In [2]:
import numpy as np
m1=[[1,2],[3,4]]
m2=[[5,6],[7,8]]
a1=np.array(m1)
a2=np.array(m2)


In [4]:
##1##
#sum of 2 matrices
sum= a1+a2
sum

array([[ 6,  8],
       [10, 12]])

In [5]:
##2##
#multiplication
np.dot(a1,a2)

array([[19, 22],
       [43, 50]])

In [6]:
##3##
# product
np.dot(a1,a2)

array([[19, 22],
       [43, 50]])

In [7]:
##4##
Add=a1+a2
print(Add)
Subtract=a1-a2
print(Subtract)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]


In [9]:
##5##
transpose=a1.transpose()
transpose

array([[1, 3],
       [2, 4]])

In [10]:
##6##
N = 4
print("The dimension : " + str(N))
res = [list(range(1 + N * i, 1 + N * (i + 1))) for i in range(N)]
print("The created matrix of N * N: " + str(res))

The dimension : 4
The created matrix of N * N: [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]


In [11]:
##7##
#to get kth column in n*m matrix
#let A be the matrix
# code is : A[0:n,k-1:k]
# To get 2nd column of matrix a1
a1[0:2,1:2]

array([[2],
       [4]])

In [14]:
##8##
stack_matrix=np.vstack((a1,a2))
print(stack_matrix)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [15]:
##9##
string="ABCDA"
if(string==string[::-1]):
      print("The string is a palindrome")
else:
      print("Not a palindrome")

Not a palindrome


In [17]:
## 10 ##
# to check whether the string is symmetry.
def symmetry(a):
     
    n = len(a)
    flag = 0
    if n%2:
        mid = n//2 +1
    else:
        mid = n//2
         
    start1 = 0
    start2 = mid
     
    while(start1 < mid and start2 < n):
         
        if (a[start1]== a[start2]):
            start1 = start1 + 1
            start2 = start2 + 1
        else:
            flag = 1
            break
    if flag == 0:
        print("The entered string is symmetrical")
    else:
        print("The entered string is not symmetrical")
        
# To check whether string is palindrome        
if(string==string[::-1]):
      print("The string is a palindrome")
else:
      print("Not a palindrome")
        
string = 'amaama'
symmetry(string)

The string is a palindrome
The entered string is symmetrical
